# Generated by Django 6.0.6 on 2026-06-05 17:16

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.BigIntegerField()),
                ('lote_id', models.BigIntegerField()),
                ('usuario_id', models.BigIntegerField()),
                ('dose', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aplicado_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTemperatura',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freezer_id', models.BigIntegerField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dentro_faixa', models.BooleanField()),
                ('registrado_em', models.DateTimeField()),
            ],
        ),
    ]
